const sampleAvatars = [
  { initials: 'AK', color: '#6366f1' },
  { initials: 'BM', color: '#34d399' },
  { initials: 'CR', color: '#f59e0b' },
  { initials: 'DJ', color: '#fb7185' },
  { initials: 'EL', color: '#818cf8' },
  { initials: 'FP', color: '#22d3ee' },
  { initials: 'GR', color: '#a78bfa' },
  { initials: 'HS', color: '#f472b6' },
  { initials: 'IT', color: '#38bdf8' },
  { initials: 'JV', color: '#34d399' },
];

const allStudents = [
  'Aarav K.', 'Bhavna M.', 'Chirag R.', 'Deepa J.', 'Eshan L.',
  'Fatima P.', 'Gaurav R.', 'Harshita S.', 'Ishaan T.', 'Jaya V.',
  'Karan S.', 'Lakshmi N.', 'Manish O.', 'Neha P.', 'Omkar R.',
  'Priya S.', 'Rahul T.', 'Sneha U.', 'Tushar V.', 'Uma W.',
  'Varun X.', 'Yash Y.', 'Zara Z.', 'Aditi K.', 'Bhuvan L.',
  'Chhavi M.', 'Divyansh N.', 'Ekta O.', 'Farhan P.', 'Geeta Q.',
  'Himmat R.', 'Isha S.', 'Jatin T.', 'Kavya U.', 'Lalit V.',
];

const generateAvatars = (count) => {
  const students = allStudents.sort(() => Math.random() - 0.5).slice(0, count);
  return students.map((name, i) => ({
    initials: name.split(' ').map(p => p[0]).join(''),
    color: sampleAvatars[i % sampleAvatars.length].color,
    name,
  }));
};

export const issueGroups = [
  {
    id: 1,
    title: 'Arduino Driver Installation Problem',
    category: 'Hardware',
    priority: 'High',
    status: 'Open',
    summary: 'Multiple students are unable to detect Arduino Uno boards after installing the IDE. The driver fails to recognize the board on both Windows and macOS systems.',
    affectedCount: 87,
    replyCount: 134,
    lastReport: '5 minutes ago',
    firstReported: 'Jul 20, 2026',
    trending: 'rising',
    impact: 'High Impact',
    aiSuggestion: {
      duplicate: true,
      similarCount: 87,
      suggestedCategory: 'Hardware',
      confidence: 98,
      suggestedResponse: 'Install CH340 Driver and verify board selection in Tools → Port.',
    },
    avatars: generateAvatars(87),
    timeline: [
      { date: 'Jul 20, 2026', event: 'First student reported Arduino not detected' },
      { date: 'Jul 21, 2026', event: '23 more students reported the same issue' },
      { date: 'Jul 22, 2026', event: 'Issue categorized as Hardware — Arduino Driver' },
      { date: 'Jul 23, 2026', event: '87 affected — escalated to High priority' },
    ],
    discussion: [
      { id: 1, from: 'student', name: 'Aarav K.', initials: 'AK', color: '#6366f1', text: 'My Arduino Uno is not showing up in the Port menu after installing the latest IDE. I tried restarting but nothing works.', timestamp: 'Jul 20, 2:15 PM' },
      { id: 2, from: 'student', name: 'Deepa J.', initials: 'DJ', color: '#fb7185', text: 'Same issue here! I\'m on Windows 11 and the device manager shows an unknown device with a yellow triangle.', timestamp: 'Jul 20, 3:40 PM' },
      { id: 3, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'Thank you for reporting. We\'re investigating this. Could all affected students please confirm their OS version?', timestamp: 'Jul 21, 9:00 AM' },
      { id: 4, from: 'student', name: 'Chirag R.', initials: 'CR', color: '#f59e0b', text: 'macOS Ventura 13.4 — same problem. The board powers up (LED on) but not recognized.', timestamp: 'Jul 21, 10:20 AM' },
      { id: 5, from: 'student', name: 'Bhavna M.', initials: 'BM', color: '#34d399', text: 'Windows 10 here. Installed the CH340 driver manually and it worked! Try that maybe?', timestamp: 'Jul 21, 11:45 AM' },
      { id: 6, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'We\'ve tested the CH340 driver solution on multiple machines. It appears to resolve the detection issue. We\'ll send a formal response shortly.', timestamp: 'Jul 22, 2:30 PM' },
      { id: 7, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'Official resolution: Install the CH340 USB-to-Serial driver from the official repository. After installation, restart the IDE and check Tools → Port. The board should appear as "COM3" (Windows) or "/dev/cu.usbserial-*" (macOS). We\'re adding this to the lab setup guide as well.', timestamp: 'Jul 22, 4:00 PM' },
    ],
    acceptedResolution: 'Install CH340 USB-to-Serial driver. Details have been added to the lab setup guide. Affected students should contact the lab assistant for hands-on help if needed.',
    relatedIssues: [
      { id: 3, title: 'ESP32 Board Not Flashing', affected: 34, status: 'Open' },
      { id: 5, title: 'Raspberry Pi SD Card Corruption', affected: 18, status: 'Resolved' },
    ],
  },
  {
    id: 2,
    title: 'WiFi Connectivity Issues in IoT Lab',
    category: 'Network',
    priority: 'Medium',
    status: 'Open',
    summary: 'Students in the IoT lab are experiencing intermittent WiFi drops. The network disconnects every 10-15 minutes during practical sessions.',
    affectedCount: 45,
    replyCount: 67,
    lastReport: '15 minutes ago',
    firstReported: 'Jul 22, 2026',
    trending: 'stable',
    impact: 'Medium Impact',
    avatars: generateAvatars(45),
    timeline: [
      { date: 'Jul 22, 2026', event: 'WiFi drops reported in IoT Lab' },
      { date: 'Jul 22, 2026', event: 'Confirmed affecting 45 students' },
      { date: 'Jul 23, 2026', event: 'IT team notified — router diagnostics scheduled' },
    ],
    discussion: [
      { id: 1, from: 'student', name: 'Fatima P.', initials: 'FP', color: '#22d3ee', text: 'The lab WiFi keeps disconnecting every 10 mins. Makes it impossible to upload code to ESP modules.', timestamp: 'Jul 22, 9:30 AM' },
      { id: 2, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'We\'ve contacted the IT department. They\'ll run diagnostics on the lab router today.', timestamp: 'Jul 22, 11:00 AM' },
    ],
    acceptedResolution: '',
    relatedIssues: [],
  },
  {
    id: 3,
    title: 'ESP32 Board Not Flashing',
    category: 'Hardware',
    priority: 'High',
    status: 'Open',
    summary: 'ESP32 development boards are failing to flash firmware. The upload process hangs at "Connecting..." and times out after 30 seconds.',
    affectedCount: 34,
    replyCount: 52,
    lastReport: '1 hour ago',
    firstReported: 'Jul 21, 2026',
    trending: 'rising',
    impact: 'High Impact',
    aiSuggestion: {
      duplicate: false,
      suggestedCategory: 'Hardware',
      confidence: 95,
      suggestedResponse: 'Hold the BOOT button while connecting, then release after upload starts.',
    },
    avatars: generateAvatars(34),
    timeline: [
      { date: 'Jul 21, 2026', event: 'ESP32 flashing failures reported' },
      { date: 'Jul 22, 2026', event: 'Confirmed on multiple boards — not a batch defect' },
      { date: 'Jul 23, 2026', event: 'Solution identified: BOOT button sequence required' },
    ],
    discussion: [
      { id: 1, from: 'student', name: 'Gaurav R.', initials: 'GR', color: '#a78bfa', text: 'My ESP32 WROOM board gets stuck at "Connecting..." every time I try to upload. Baud rate 115200.', timestamp: 'Jul 21, 4:20 PM' },
      { id: 2, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'Try holding the BOOT button, press RESET, release BOOT. This puts the board in flash mode.', timestamp: 'Jul 22, 10:15 AM' },
    ],
    acceptedResolution: 'Hold BOOT button → press RESET → release BOOT. This enters flash mode. Ensure correct board selection in Tools → Board → ESP32 Dev Module.',
    relatedIssues: [
      { id: 1, title: 'Arduino Driver Installation Problem', affected: 87, status: 'Open' },
    ],
  },
  {
    id: 4,
    title: 'Missing Components in Robotics Kit',
    category: 'Inventory',
    priority: 'Medium',
    status: 'Open',
    summary: 'Several robotics kits are missing essential components like ultrasonic sensors, motor drivers, and jumper wires.',
    affectedCount: 28,
    replyCount: 41,
    lastReport: '2 hours ago',
    firstReported: 'Jul 19, 2026',
    trending: 'declining',
    impact: 'Medium Impact',
    avatars: generateAvatars(28),
    timeline: [
      { date: 'Jul 19, 2026', event: 'Missing components reported in Kit #12-18' },
      { date: 'Jul 20, 2026', event: 'Inventory audit initiated for all robotics kits' },
      { date: 'Jul 22, 2026', event: 'Procurement request submitted for replacement parts' },
    ],
    discussion: [
      { id: 1, from: 'student', name: 'Harshita S.', initials: 'HS', color: '#f472b6', text: 'Kit #14 is missing the HC-SR04 ultrasonic sensor. Can I get a replacement?', timestamp: 'Jul 19, 3:00 PM' },
      { id: 2, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'We\'ve ordered replacement components. ETA is 3-5 working days. We\'ll notify once they arrive.', timestamp: 'Jul 20, 9:45 AM' },
    ],
    acceptedResolution: 'Replacement components ordered (PO #INV-2026-089). Expected delivery by Jul 28. Students without complete kits can use the lab spare set temporarily.',
    relatedIssues: [
      { id: 5, title: 'Raspberry Pi SD Card Corruption', affected: 18, status: 'Resolved' },
    ],
  },
  {
    id: 5,
    title: 'Raspberry Pi SD Card Corruption',
    category: 'Hardware',
    priority: 'Low',
    status: 'Resolved',
    summary: 'SD cards in Raspberry Pi 4 units are getting corrupted after improper shutdown. Multiple students lost project data.',
    affectedCount: 18,
    replyCount: 29,
    lastReport: '1 day ago',
    firstReported: 'Jul 15, 2026',
    trending: 'resolved',
    impact: 'Resolved',
    avatars: generateAvatars(18),
    timeline: [
      { date: 'Jul 15, 2026', event: 'SD card corruption reported' },
      { date: 'Jul 16, 2026', event: 'Root cause: improper shutdown without fsck' },
      { date: 'Jul 18, 2026', event: 'Solution: safe shutdown procedure documented' },
      { date: 'Jul 20, 2026', event: 'Auto-fsck enabled on all RPis — issue resolved' },
    ],
    discussion: [
      { id: 1, from: 'student', name: 'Ishaan T.', initials: 'IT', color: '#38bdf8', text: 'My RPi won\'t boot. Getting kernel panic on SD card. I had my project files on it.', timestamp: 'Jul 15, 11:20 AM' },
      { id: 2, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'We\'ve identified the issue. The SD cards need proper shutdown (sudo shutdown -h now). We\'ve enabled auto-fsck on boot to prevent this.', timestamp: 'Jul 18, 2:00 PM' },
    ],
    acceptedResolution: 'Auto-fsck enabled on all Raspberry Pi units. Students must use the shutdown button on the desktop or run "sudo shutdown -h now" before removing power. Data recovery available at lab desk.',
    relatedIssues: [],
  },
  {
    id: 6,
    title: 'Lab Access Card Not Working',
    category: 'Access',
    priority: 'High',
    status: 'Open',
    summary: 'Several students\' access cards are not working for the after-hours IoT lab entry. Cards show "Invalid" on the reader.',
    affectedCount: 22,
    replyCount: 18,
    lastReport: '3 hours ago',
    firstReported: 'Jul 23, 2026',
    trending: 'rising',
    impact: 'High Impact',
    avatars: generateAvatars(22),
    timeline: [
      { date: 'Jul 23, 2026', event: 'Access card failures reported for IoT lab' },
      { date: 'Jul 23, 2026', event: 'Security system upgrade may have invalidated old cards' },
    ],
    discussion: [
      { id: 1, from: 'student', name: 'Jaya V.', initials: 'JV', color: '#34d399', text: 'My card worked yesterday but today it shows "Invalid" on the IoT lab door. Can this be fixed?', timestamp: 'Jul 23, 8:15 AM' },
      { id: 2, from: 'admin', name: 'Admin', initials: 'AD', color: '#6366f1', text: 'We\'re aware of the issue. The security system was upgraded last night. Affected cards need to be re-registered. Please visit the lab desk.', timestamp: 'Jul 23, 9:30 AM' },
    ],
    acceptedResolution: '',
    relatedIssues: [],
  },
];

export const issueFilters = {
  categories: ['Hardware', 'Network', 'Inventory', 'Access', 'Software', 'Other'],
  priorities: ['High', 'Medium', 'Low'],
  statuses: ['Open', 'Resolved'],
  sortOptions: [
    { value: 'newest', label: 'Newest' },
    { value: 'most_reported', label: 'Most Reported' },
    { value: 'trending', label: 'Trending' },
    { value: 'resolved', label: 'Resolved' },
  ],
};

export const supportStats = {
  openIssueGroups: 5,
  affectedStudents: 216,
  resolvedIssues: 1,
  avgResolutionTime: '3.4 Hours',
};
