"""updating databse

Revision ID: 12d11e36c9a6
Revises: c19d8329b31e
Create Date: 2026-08-23 13:32:49.699708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d11e36c9a6'
down_revision: Union[str, None] = 'c19d8329b31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_reject_reasons_event_id_key'), 'event_reject_reasons', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('event_reject_reasons_event_id_key'), 'event_reject_reasons', ['event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
