"""Event details

Revision ID: 40fcd0a1660a
Revises: bac5a379286f
Create Date: 2026-08-03 10:45:52.097623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '40fcd0a1660a'
down_revision: Union[str, None] = 'bac5a379286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('workshop', 'hackathon', 'seminar', 'competition', 'bootcamp', 'webinar', 'robotics', 'other', name='event_category'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.Enum('seminar_hall', 'auditorium', 'main_ground', 'computer_lab_1', 'computer_lab_2', 'robotics_lab', 'innovation_lab', 'conference_room', 'classroom', 'online', 'other', name='event_venue'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='event_status'), server_default='pending', nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_event_info',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('section_type', sa.Enum('learning', 'requirement', 'eligibility', name='additional_info_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_event_info_event_id'), 'additional_event_info', ['event_id'], unique=False)
    op.create_table('event_agenda_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_agenda_schedule_event_id'), 'event_agenda_schedule', ['event_id'], unique=False)
    op.create_table('event_mentors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_mentors_event_id'), 'event_mentors', ['event_id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sa.String(length=150), nullable=False),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('registration_status', sa.Enum('pending', 'registered', name='registration_status'), server_default='pending', nullable=False),
    sa.Column('attendance_status', sa.Enum('absent', 'present', name='attendance_status'), server_default='absent', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_student_id'), 'event_registrations', ['student_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sa.Enum('web_development', 'app_development', 'ai_ml', 'data_science', 'cyber_security', 'cloud_computing', 'devops', 'ui_ux_design', 'robotics', 'iot', 'competitive_programming', 'blockchain', 'game_development', 'other', name='skill'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    op.create_table('event_winners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Enum('first', 'second', 'third', name='winner_position'), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'position', name='uq_event_winners_event_position'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_index(op.f('ix_event_winners_event_id'), 'event_winners', ['event_id'], unique=False)
    op.add_column('students', sa.Column('student_id', sa.String(length=20), nullable=False))
    department = postgresql.ENUM('computer_science', 'information_technology', 'electronics', 'electrical', 'mechanical', 'civil', 'chemical', 'biotechnology', 'mathematics', 'physics', 'other', name='department', create_type=False)
    department.create(op.get_bind(), checkfirst=True)
    op.add_column('students', sa.Column('department', department, nullable=False))
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'department')
    postgresql.ENUM(name='department').drop(op.get_bind(), checkfirst=True)
    op.drop_column('students', 'student_id')
    op.drop_index(op.f('ix_event_winners_event_id'), table_name='event_winners')
    op.drop_table('event_winners')
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_event_registrations_student_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_event_mentors_event_id'), table_name='event_mentors')
    op.drop_table('event_mentors')
    op.drop_index(op.f('ix_event_agenda_schedule_event_id'), table_name='event_agenda_schedule')
    op.drop_table('event_agenda_schedule')
    op.drop_index(op.f('ix_additional_event_info_event_id'), table_name='additional_event_info')
    op.drop_table('additional_event_info')
    op.drop_table('events')
    # ### end Alembic commands ###
