"""add inventory support bounty tables

Revision ID: b48f60142cf2
Revises: 40fcd0a1660a
Create Date: 2026-08-16 21:30:59.796708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b48f60142cf2'
down_revision: Union[str, None] = '40fcd0a1660a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('PROGRAMMING_LANGUAGES', 'WEB_DEVELOPMENT', 'BACKEND_DEVELOPMENT', 'APP_DEVELOPMENT', 'AI_ML', 'DATA_SCIENCE', 'CYBER_SECURITY', 'CLOUD_COMPUTING', 'DEVOPS', 'DATABASE', 'UI_UX_DESIGN', 'ROBOTICS', 'IOT', 'BLOCKCHAIN', 'GAME_DEVELOPMENT', 'COMPETITIVE_PROGRAMMING', 'VOLUNTEERING', name='domain_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=150), nullable=True),
    sa.Column('equipment_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bounties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reward', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('student_seats', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'in_progress', 'completed', 'cancelled', name='bounty_status'), server_default='open', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_created_by'), 'bounties', ['created_by'], unique=False)
    op.create_index(op.f('ix_bounties_domain_id'), 'bounties', ['domain_id'], unique=False)
    op.create_table('discussion_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('PYTHON', 'JAVA', 'C', 'CPP', 'C_SHARP', 'JAVASCRIPT', 'TYPESCRIPT', 'GO', 'RUST', 'PHP', 'KOTLIN', 'SWIFT', 'DART', 'R', 'HTML', 'CSS', 'TAILWIND_CSS', 'BOOTSTRAP', 'REACT', 'NEXT_JS', 'VUE_JS', 'NUXT_JS', 'ANGULAR', 'SVELTE', 'NODE_JS', 'EXPRESS_JS', 'FASTAPI', 'FLASK', 'DJANGO', 'SPRING_BOOT', 'NEST_JS', 'LARAVEL', 'ASP_NET', 'GRAPHQL', 'REST_API', 'FLUTTER', 'REACT_NATIVE', 'ANDROID', 'JETPACK_COMPOSE', 'SWIFT_UI', 'NUMPY', 'PANDAS', 'SCIKIT_LEARN', 'TENSORFLOW', 'PYTORCH', 'KERAS', 'OPENCV', 'LANGCHAIN', 'HUGGING_FACE', 'OPENAI_API', 'MATPLOTLIB', 'SEABORN', 'POWER_BI', 'TABLEAU', 'JUPYTER', 'KALI_LINUX', 'WIRESHARK', 'BURP_SUITE', 'NMAP', 'METASPLOIT', 'OWASP', 'AWS', 'AZURE', 'GOOGLE_CLOUD', 'FIREBASE', 'SUPABASE', 'DOCKER', 'KUBERNETES', 'JENKINS', 'GITHUB_ACTIONS', 'TERRAFORM', 'ANSIBLE', 'NGINX', 'LINUX', 'POSTGRESQL', 'MYSQL', 'SQLITE', 'MONGODB', 'REDIS', 'ORACLE', 'SQL_SERVER', 'FIGMA', 'ADOBE_XD', 'CANVA', 'PHOTOSHOP', 'ILLUSTRATOR', 'ROS', 'ARDUINO', 'RASPBERRY_PI', 'ESP32', 'MQTT', 'SOLIDITY', 'HARDHAT', 'FOUNDRY', 'ETHERS_JS', 'WEB3_JS', 'UNITY', 'UNREAL_ENGINE', 'GODOT', 'BLENDER', 'CODEFORCES', 'CODECHEF', 'LEETCODE', 'ATCODER', 'HACKERRANK', 'EVENT_COORDINATION', 'EVENT_MANAGEMENT', 'HELP_DESK', 'CROWD_MANAGEMENT', 'VENUE_MANAGEMENT', 'STAGE_MANAGEMENT', 'LOGISTICS', 'EQUIPMENT_HANDLING', 'GUEST_MANAGEMENT', 'PARTICIPANT_COORDINATION', 'ATTENDANCE_MANAGEMENT', 'TECHNICAL_SUPPORT', 'PHOTOGRAPHY', 'VIDEOGRAPHY', 'SOCIAL_MEDIA_COVERAGE', 'CONTENT_CREATION', 'POSTER_DESIGN', 'MARKETING', 'SPONSOR_COORDINATION', name='technology_enum'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name', name='uq_technologies_domain_name')
    )
    op.create_index(op.f('ix_technologies_domain_id'), 'technologies', ['domain_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bounty_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='application_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bounty_id', 'student_id', name='uq_applications_bounty_student')
    )
    op.create_index(op.f('ix_applications_bounty_id'), 'applications', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('borrow_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('borrowed_quantity', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_details_equipment_id'), 'borrow_details', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_borrow_details_student_id'), 'borrow_details', ['student_id'], unique=False)
    op.create_table('bounty_technologies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bounty_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bounty_id', 'technology_id', name='uq_bounty_technologies_bounty_technology')
    )
    op.create_index(op.f('ix_bounty_technologies_bounty_id'), 'bounty_technologies', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_technologies_technology_id'), 'bounty_technologies', ['technology_id'], unique=False)
    op.create_table('discussion_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['discussion_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_messages_parent_message_id'), 'discussion_messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_thread_id'), 'discussion_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_user_id'), 'discussion_messages', ['user_id'], unique=False)
    op.create_table('responsibilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bounty_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsibilities_bounty_id'), 'responsibilities', ['bounty_id'], unique=False)
    op.create_table('student_domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'domain_id', name='uq_student_domains_student_domain')
    )
    op.create_index(op.f('ix_student_domains_domain_id'), 'student_domains', ['domain_id'], unique=False)
    op.create_index(op.f('ix_student_domains_student_id'), 'student_domains', ['student_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_type', sa.Enum('participation', 'first', 'second', 'third', name='certificate_type'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_index(op.f('ix_certificates_event_id'), 'certificates', ['event_id'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('student_technologies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_domain_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_domain_id'], ['student_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_domain_id', 'technology_id', name='uq_student_technologies_student_domain_technology')
    )
    op.create_index(op.f('ix_student_technologies_student_domain_id'), 'student_technologies', ['student_domain_id'], unique=False)
    op.create_index(op.f('ix_student_technologies_technology_id'), 'student_technologies', ['technology_id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', name='work_status'), server_default='assigned', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_application_id'), 'works', ['application_id'], unique=True)
    op.create_index(op.f('ix_works_event_id'), 'works', ['event_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='deliverable_status'), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_work_id'), 'deliverables', ['work_id'], unique=False)
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.add_column('students', sa.Column('github_url', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('linkedin_url', sa.String(length=100), nullable=True))
    op.drop_column('students', 'linkedin_username')
    op.drop_column('students', 'github_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('github_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('linkedin_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('students', 'linkedin_url')
    op.drop_column('students', 'github_url')
    op.create_table('student_skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill', postgresql.ENUM('web_development', 'app_development', 'ai_ml', 'data_science', 'cyber_security', 'cloud_computing', 'devops', 'ui_ux_design', 'robotics', 'iot', 'competitive_programming', 'blockchain', 'game_development', 'other', name='skill'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_skills_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_skills_pkey'))
    )
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    op.drop_index(op.f('ix_deliverables_work_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_works_event_id'), table_name='works')
    op.drop_index(op.f('ix_works_application_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_student_technologies_technology_id'), table_name='student_technologies')
    op.drop_index(op.f('ix_student_technologies_student_domain_id'), table_name='student_technologies')
    op.drop_table('student_technologies')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_event_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_student_domains_student_id'), table_name='student_domains')
    op.drop_index(op.f('ix_student_domains_domain_id'), table_name='student_domains')
    op.drop_table('student_domains')
    op.drop_index(op.f('ix_responsibilities_bounty_id'), table_name='responsibilities')
    op.drop_table('responsibilities')
    op.drop_index(op.f('ix_discussion_messages_user_id'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_thread_id'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_parent_message_id'), table_name='discussion_messages')
    op.drop_table('discussion_messages')
    op.drop_index(op.f('ix_bounty_technologies_technology_id'), table_name='bounty_technologies')
    op.drop_index(op.f('ix_bounty_technologies_bounty_id'), table_name='bounty_technologies')
    op.drop_table('bounty_technologies')
    op.drop_index(op.f('ix_borrow_details_student_id'), table_name='borrow_details')
    op.drop_index(op.f('ix_borrow_details_equipment_id'), table_name='borrow_details')
    op.drop_table('borrow_details')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_bounty_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_technologies_domain_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_table('discussion_threads')
    op.drop_index(op.f('ix_bounties_domain_id'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_created_by'), table_name='bounties')
    op.drop_table('bounties')
    op.drop_table('equipment')
    op.drop_table('domains')
    # ### end Alembic commands ###
