export const DOMAINS = [
  { value: 'PROGRAMMING_LANGUAGES', label: 'Programming Languages', icon: 'bi-code-slash' },
  { value: 'WEB_DEVELOPMENT', label: 'Web Development', icon: 'bi-globe' },
  { value: 'BACKEND_DEVELOPMENT', label: 'Backend Development', icon: 'bi-hdd-network' },
  { value: 'APP_DEVELOPMENT', label: 'App Development', icon: 'bi-phone' },
  { value: 'AI_ML', label: 'AI & Machine Learning', icon: 'bi-cpu' },
  { value: 'DATA_SCIENCE', label: 'Data Science & Analytics', icon: 'bi-bar-chart-line' },
  { value: 'CYBER_SECURITY', label: 'Cyber Security', icon: 'bi-shield-lock' },
  { value: 'CLOUD_COMPUTING', label: 'Cloud Computing', icon: 'bi-cloud' },
  { value: 'DEVOPS', label: 'DevOps & CI/CD', icon: 'bi-diagram-3' },
  { value: 'DATABASE', label: 'Database Systems', icon: 'bi-database' },
  { value: 'UI_UX_DESIGN', label: 'UI / UX Design', icon: 'bi-palette' },
  { value: 'ROBOTICS', label: 'Robotics', icon: 'bi-robot' },
  { value: 'IOT', label: 'Internet of Things (IoT)', icon: 'bi-wifi' },
  { value: 'BLOCKCHAIN', label: 'Blockchain & Web3', icon: 'bi-link' },
  { value: 'GAME_DEVELOPMENT', label: 'Game Development', icon: 'bi-controller' },
  { value: 'COMPETITIVE_PROGRAMMING', label: 'Competitive Programming', icon: 'bi-trophy' },
];

export const DOMAIN_TECHNOLOGIES = {
  PROGRAMMING_LANGUAGES: [
    { value: 'PYTHON', label: 'Python' },
    { value: 'JAVA', label: 'Java' },
    { value: 'C', label: 'C' },
    { value: 'CPP', label: 'C++' },
    { value: 'C_SHARP', label: 'C#' },
    { value: 'JAVASCRIPT', label: 'JavaScript' },
    { value: 'TYPESCRIPT', label: 'TypeScript' },
    { value: 'GO', label: 'Go' },
    { value: 'RUST', label: 'Rust' },
    { value: 'PHP', label: 'PHP' },
    { value: 'KOTLIN', label: 'Kotlin' },
    { value: 'SWIFT', label: 'Swift' },
    { value: 'DART', label: 'Dart' },
    { value: 'R', label: 'R' },
  ],
  WEB_DEVELOPMENT: [
    { value: 'HTML', label: 'HTML5' },
    { value: 'CSS', label: 'CSS3' },
    { value: 'TAILWIND_CSS', label: 'Tailwind CSS' },
    { value: 'BOOTSTRAP', label: 'Bootstrap' },
    { value: 'REACT', label: 'React.js' },
    { value: 'NEXT_JS', label: 'Next.js' },
    { value: 'VUE_JS', label: 'Vue.js' },
    { value: 'NUXT_JS', label: 'Nuxt.js' },
    { value: 'ANGULAR', label: 'Angular' },
    { value: 'SVELTE', label: 'Svelte' },
  ],
  BACKEND_DEVELOPMENT: [
    { value: 'NODE_JS', label: 'Node.js' },
    { value: 'EXPRESS_JS', label: 'Express.js' },
    { value: 'FASTAPI', label: 'FastAPI' },
    { value: 'FLASK', label: 'Flask' },
    { value: 'DJANGO', label: 'Django' },
    { value: 'SPRING_BOOT', label: 'Spring Boot' },
    { value: 'NEST_JS', label: 'NestJS' },
    { value: 'LARAVEL', label: 'Laravel' },
    { value: 'ASP_NET', label: 'ASP.NET Core' },
    { value: 'GRAPHQL', label: 'GraphQL' },
    { value: 'REST_API', label: 'REST APIs' },
  ],
  APP_DEVELOPMENT: [
    { value: 'FLUTTER', label: 'Flutter' },
    { value: 'REACT_NATIVE', label: 'React Native' },
    { value: 'ANDROID', label: 'Android Native' },
    { value: 'JETPACK_COMPOSE', label: 'Jetpack Compose' },
    { value: 'SWIFT_UI', label: 'SwiftUI' },
  ],
  AI_ML: [
    { value: 'NUMPY', label: 'NumPy' },
    { value: 'PANDAS', label: 'Pandas' },
    { value: 'SCIKIT_LEARN', label: 'Scikit-Learn' },
    { value: 'TENSORFLOW', label: 'TensorFlow' },
    { value: 'PYTORCH', label: 'PyTorch' },
    { value: 'KERAS', label: 'Keras' },
    { value: 'OPENCV', label: 'OpenCV' },
    { value: 'LANGCHAIN', label: 'LangChain' },
    { value: 'HUGGING_FACE', label: 'Hugging Face' },
    { value: 'OPENAI_API', label: 'OpenAI API' },
  ],
  DATA_SCIENCE: [
    { value: 'MATPLOTLIB', label: 'Matplotlib' },
    { value: 'SEABORN', label: 'Seaborn' },
    { value: 'POWER_BI', label: 'Power BI' },
    { value: 'TABLEAU', label: 'Tableau' },
    { value: 'JUPYTER', label: 'Jupyter Notebooks' },
  ],
  CYBER_SECURITY: [
    { value: 'KALI_LINUX', label: 'Kali Linux' },
    { value: 'WIRESHARK', label: 'Wireshark' },
    { value: 'BURP_SUITE', label: 'Burp Suite' },
    { value: 'NMAP', label: 'Nmap' },
    { value: 'METASPLOIT', label: 'Metasploit' },
    { value: 'OWASP', label: 'OWASP' },
  ],
  CLOUD_COMPUTING: [
    { value: 'AWS', label: 'AWS' },
    { value: 'AZURE', label: 'Microsoft Azure' },
    { value: 'GOOGLE_CLOUD', label: 'Google Cloud (GCP)' },
    { value: 'FIREBASE', label: 'Firebase' },
    { value: 'SUPABASE', label: 'Supabase' },
  ],
  DEVOPS: [
    { value: 'DOCKER', label: 'Docker' },
    { value: 'KUBERNETES', label: 'Kubernetes' },
    { value: 'JENKINS', label: 'Jenkins' },
    { value: 'GITHUB_ACTIONS', label: 'GitHub Actions' },
    { value: 'TERRAFORM', label: 'Terraform' },
    { value: 'ANSIBLE', label: 'Ansible' },
    { value: 'NGINX', label: 'NGINX' },
    { value: 'LINUX', label: 'Linux Server' },
  ],
  DATABASE: [
    { value: 'POSTGRESQL', label: 'PostgreSQL' },
    { value: 'MYSQL', label: 'MySQL' },
    { value: 'SQLITE', label: 'SQLite' },
    { value: 'MONGODB', label: 'MongoDB' },
    { value: 'REDIS', label: 'Redis' },
    { value: 'ORACLE', label: 'Oracle DB' },
    { value: 'SQL_SERVER', label: 'Microsoft SQL Server' },
  ],
  UI_UX_DESIGN: [
    { value: 'FIGMA', label: 'Figma' },
    { value: 'ADOBE_XD', label: 'Adobe XD' },
    { value: 'CANVA', label: 'Canva' },
    { value: 'PHOTOSHOP', label: 'Photoshop' },
    { value: 'ILLUSTRATOR', label: 'Illustrator' },
  ],
  ROBOTICS: [
    { value: 'ROS', label: 'ROS / ROS 2' },
    { value: 'ARDUINO', label: 'Arduino' },
    { value: 'RASPBERRY_PI', label: 'Raspberry Pi' },
  ],
  IOT: [
    { value: 'ESP32', label: 'ESP32' },
    { value: 'MQTT', label: 'MQTT' },
  ],
  BLOCKCHAIN: [
    { value: 'SOLIDITY', label: 'Solidity' },
    { value: 'HARDHAT', label: 'Hardhat' },
    { value: 'FOUNDRY', label: 'Foundry' },
    { value: 'ETHERS_JS', label: 'Ethers.js' },
    { value: 'WEB3_JS', label: 'Web3.js' },
  ],
  GAME_DEVELOPMENT: [
    { value: 'UNITY', label: 'Unity 3D' },
    { value: 'UNREAL_ENGINE', label: 'Unreal Engine' },
    { value: 'GODOT', label: 'Godot' },
    { value: 'BLENDER', label: 'Blender' },
  ],
  COMPETITIVE_PROGRAMMING: [
    { value: 'CODEFORCES', label: 'Codeforces' },
    { value: 'CODECHEF', label: 'CodeChef' },
    { value: 'LEETCODE', label: 'LeetCode' },
    { value: 'ATCODER', label: 'AtCoder' },
    { value: 'HACKERRANK', label: 'HackerRank' },
  ],
};

export const DEPARTMENTS = [
  { value: 'computer_science', label: 'Computer Science' },
  { value: 'information_technology', label: 'Information Technology' },
  { value: 'electronics', label: 'Electronics Engineering' },
  { value: 'electrical', label: 'Electrical Engineering' },
  { value: 'mechanical', label: 'Mechanical Engineering' },
  { value: 'civil', label: 'Civil Engineering' },
  { value: 'chemical', label: 'Chemical Engineering' },
  { value: 'biotechnology', label: 'Biotechnology' },
  { value: 'mathematics', label: 'Mathematics' },
  { value: 'physics', label: 'Physics' },
  { value: 'other', label: 'Other' },
];
